### Import necessary Packages:

In [199]:
from selenium import webdriver
import time
import pandas as pd

### Setup Web-Driver:

In [200]:
search_query = 'https://www.indeed.com/q-data-scientist-jobs.html'
driver = webdriver.Chrome(executable_path='C:/Users/Aishwarya/Downloads/chromedriver.exe')

driver.get(search_query)
driver.maximize_window()

time.sleep(5)

### Scrape data from the web-page:

In [201]:
job_details = []
job_info = []

#list of all jobs with their elements
job_list = driver.find_elements_by_xpath("//div[@class='job_seen_beacon']")
for job in job_list:
    
    #job Title
    title = job.find_elements_by_xpath(".//div/h2/span")[0]
    
    #Company Name
    company=job.find_elements_by_xpath(".//div[@class='heading6 company_location tapItem-gutter']//span")[0]
    #rating = job.find_elements_by_xpath(".//span[@class='ratingNumber']/span")[0]
    
    #Job Location
    location= job.find_elements_by_xpath(".//div[@class='companyLocation']")[0]
    
    #Job Posting Date
    posting_date = job.find_elements_by_xpath(".//span[@class='date']")[0]
    
    #Job Summary
    summary = job.find_elements_by_xpath(".//div[@class='job-snippet']")[0]
    
    job_info = [title.text, company.text, location.text, summary.text, posting_date.text]
    job_details.append(job_info)

In [202]:
next_page_button = driver.find_element_by_class_name('pn')

#click on the button for next page
next_page_button.click()

time.sleep(5)

In [205]:
#close the popup
close_button= driver.find_elements_by_xpath("//button[@class='popover-x-button-close icl-CloseButton']")[0]
close_button.click()

In [206]:
#list of all jobs with their elements for the next page
job_list = driver.find_elements_by_xpath("//div[@class='job_seen_beacon']")
for job in job_list:
    
    #job Title
    title = job.find_elements_by_xpath(".//div/h2/span")[0]
    
    #Company Name
    company=job.find_elements_by_xpath(".//div[@class='heading6 company_location tapItem-gutter']//span")[0]
    #rating = job.find_elements_by_xpath(".//span[@class='ratingNumber']/span")[0]
    
    #Job Location
    location= job.find_elements_by_xpath(".//div[@class='companyLocation']")[0]
    
    #Job Posting Date
    posting_date = job.find_elements_by_xpath(".//span[@class='date']")[0]
    
    #Job Summary
    summary = job.find_elements_by_xpath(".//div[@class='job-snippet']")[0]
    
    job_info = [title.text, company.text, location.text, summary.text, posting_date.text]
    job_details.append(job_info)

In [207]:
#construct the dataframe
df = pd.DataFrame(job_details, columns= ['Job Title', 'Company', 'Location', 'Summary', 'Posting Date'])

#close the driver
driver.quit()

#display the dataframe
job_details_df

,Job Title,Company,Location,Summary,Posting Date
0,Data Scientist,Activision,"Foster City, CA",Develop novel analytics to qualitatively deduc...,Today
1,Graduate Data Scientist,Mars,"New York, NY",Build understanding of the Mars Petcare data e...,4 days ago
2,Entry Level Data Scientist,Toyota Connected North America,"Plano, TX•Remote",Perform data analysis and derive meaningful in...,1 day ago
3,Junior Data Scientist,Toyota,"Plano, TX 75023",Comprehensive health care and wellness plans f...,7 days ago
4,Data Scientist,Central Intelligence Agency,"Washington, DC 20505 (Foggy Bottom area)",Our benefits support every aspect of a working...,30+ days ago
5,"Data Scientist, Dolby.io",Dolby,"San Francisco, CA",With an eye to capture analytics value for the...,20 days ago
6,Data Scientist,TurnPoint,"Atlanta, GA 30318+2 locations",Data scientists have a wide range of technical...,Just posted
7,Associate Data Scientist,WALGREENS,"Chicago, IL 60603 (The Loop area)",Develops basic tests and validates hypotheses ...,3 days ago
8,Data Scientist,Doosan Bobcat,"West Fargo, ND 58078+1 location",The PIT Data Scientist is responsible for expl...,Just posted
9,Senior Data Scientist,Soaren Management,"Scottsdale, AZ 85254 (Paradise Valley area)•Te...",We are currently looking for an experienced Se...,Just posted
10,Data Scientist,Lake Washington School District,"Redmond, WA",Three (3) years of experience developing deliv...,25 days ago
11,Data Scientist,Warner Music Group,"New York, NY",The Research + Analysis department works to in...,19 days ago
12,Senior Data Analyst,Medely Inc.,Remote•Remote,Ability to analyze data and condense data to t...,Active 4 days ago
13,Data Scientist III-Remote,John Deere,"Cary, NC 27518•Remote",Create and implement algorithms which manage t...,1 day ago
14,[Parade] Data Scientist,RocketPower,Remote•Remote,We’re looking for a data scientist with strong...,1 day ago
15,Data Scientist,eHealth,"Santa Clara, CA",Participate in all aspects of the project life...,28 days ago
16,Data Scientist,Pluto TV,"Los Angeles, CA 90069",1 to 3 years of commercial experience in a dat...,1 day ago
17,Data Scientist,HarperCollins Publishers,"New York, NY 10007 (Financial District area)","Use machine learning, data mining, and statist...",30+ days ago
18,Data Scientist GS-12/13/14,Federal Bureau of Investigation,"Pocatello, ID 83201","Provide scientific, statistical, and technical...",Just posted
19,Data Scientist II,Aristocrat Technologies,"Las Vegas, NV",Lead the technical evaluation and recommendati...,Today
20,Senior Data Scientist,Endeavor,"New York, NY",Job Description Endeavor is an equal opportuni...,5 days ago
21,Data Scientist,"Grammarly, Inc.","San Francisco, CA 94104 (Financial District ar...",Has deep knowledge and command of product usag...,30+ days ago
22,Data Scientist,John Deere,"Johnston, IA 50131","Develop, implement, and manage credit scoring ...",30+ days ago
23,"Data Scientist, Product Analytics (Remote - U.S.)",Atlassian,"New York, NY",Play with our seriously large volume of analyt...,6 days ago
24,Data Scientist,Toyota,"Plano, TX 75023",Comprehensive health care and wellness plans f...,18 days ago
25,Data Scientists,Brillio,"Tampa, FL","Key Skills > Python, TensorFlow, SQL Good to h...",Just posted
26,Data Scientist,"comScore, Inc.","New York, NY 10001 (Garment District area)",Expertise at querying and manipulating data in...,Today
27,Data Scientist,Zest AI,"Burbank, CA",Translate unstructured business problems into ...,3 days ago
28,Data Scientist,Digitas,"New York, NY 10104 (Midtown area)","We build inferential and predictive models, in...",27 days ago
29,Data Scientist,Charles Schwab,"Austin, TX",3-5 years’ of experience in a data engineering...,14 days ago

### Save the data to Excel:

In [209]:
df.to_excel('Indeed_DataScientist_Jobs.xlsx', index= False)